# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Template Challenge
short_description: Predict XXX from XXX
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: We use the XXX metric for evaluation 
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["accuracy"],
        "default_order_by": "accuracy",
      }

challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2019-01-19 00:00:00
    end_date: 2099-04-25 23:59:59
    test_annotation_file: annotations/valid.csv
    codename: dev
    max_submissions_per_day: 100
    max_submissions_per_month: 50
    max_submissions: 50
    submission_meta_attributes: null
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
  - id: 2
    name: Test Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: False
    is_public: False
    is_submission_public: False
    start_date: 2019-01-19 00:00:00
    end_date: 2099-04-25 23:59:59
    test_annotation_file: annotations/test.csv
    codename: test
    max_submissions_per_day: 100
    max_submissions_per_month: 50
    max_submissions: 50
    submission_meta_attributes: null
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Valid Split
    codename: dev
  - id: 2
    name: Test Split
    codename: test

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 3
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: true
